url: "http://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-3--Jonoboo" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

navigation:
  - title: Spring
    url: /spring.html
  - title: Autumn
    url: /autumn.html
  - title: Summer
    url: /summer.html
  - title: Winter 
    url: /winter.html
